package com.denchic45.financetracker.ui.icon

val AppIcons.CategorizedIcons
    get() = AppIcons.AllIconsNamed.filterKeys { it in categorizedIconNames }

val categorizedIconNames = setOf(
    // Symbols
    "yin-yang",
    "venus",
    "mars",
    "radioactive",
    // Food
    "cup",
    "baguette",
    "bottle",
    "apple",
    "carrot",
    "lemon-2",
    "lemon",
    "glass-full",
    "bread",
    "bubble-tea",
    "glass-gin",
    "glass-cocktail",
    "burger",
    "meat",
    "milk",
    "pizza",
    "ice-cream",
    "cheese",
    "cake",
    // Nature
    "cannabis",
    "cherry",
    "leaf",
    "christmas-tree",
    // Vehicles
    "garden-cart",
    "motorbike",
    "backhoe",
    "bike",
    "bus",
    "aerial-lift",
    "air-balloon",
    "car",
    "gas-station",
    // Communication
    "mail",
    // Health
    "smoking",
    "first-aid-kit",
    "bandage",
    "brain",
    "baby-carriage",
    "massage",
    "dental",
    "eyeglass",
    "flask",
    "pill",
    "skull",
    // System
    "lock",
    "alert-triangle",
    // Media
    "video",
    "photo",
    "microphone",
    "speakerphone",
    "radio",
    "movie",
    "music",
    // Design
    "brush",
    "cut",
    "scissors",
    "cards",
    // Games
    "axe",
    "piano",
    "play-card",
    "horse-toy",
    // Buildings
    "building-bank",
    "building-stadium",
    "building-hospital",
    "building-bridge",
    "home",
    "building-circus",
    "podium",
    "building-carousel",
    // Map
    "anchor",
    "masks-theater",
    "tree",
    "beach",
    "world",
    // Sport
    "ball-volleyball",
    "chess-king",
    "ball-basketball",
    "chess",
    "golf",
    "ball-football",
    "chess-knight",
    "barbell",
    "ball-tennis",
    "ball-bowling",
    "ball-american-football",
    "ball-baseball",
    "ping-pong",
    "ice-skating",
    // Animals
    "pig-money",
    "cat",
    "spider",
    // Text
    "ballpen",
    "language",
    // Devices
    "device-laptop",
    "device-gamepad",
    "access-point",
    "blender",
    "device-speaker",
    // Development
    "bug",
    "terminal-2",
    "ai",
    "apps",
    // E-commerce
    "gift",
    "backpack",
    "hanger",
    "shoe",
    "shopping-cart",
    "shopping-bag",
    "shirt",
    // Document
    "book",
    "book-2",
    "books",
    // Weather
    "snowflake",
    "cloud",
    "flare",
    "sun",
    // No category
    "friends",
    "moneybag",
    "paw",
    "umbrella",
    "binoculars",
    "armchair",
    "sofa",
    "gavel",
    "sos",
    "activity",
    "armchair-2",
    "bath",
    "shovel",
    "award",
    "device-watch",
    "lighter",
    "poo",
    "man",
    "alien",
    "briefcase"
)