package com.denchic45.financetracker.ui

import financetracker_app.shared.generated.resources.Res
import financetracker_app.shared.generated.resources.allDrawableResources

val categorizedIconNames = setOf(
    // Buildings
    "building_bridge",
    "podium",
    "building_bank",
    "building_hospital",
    "building_stadium",
    "home",
    "building_circus",
    "building_community",
    "building_carousel",
    // E_commerce
    "backpack",
    "hanger",
    "shoe",
    "shopping_bag",
    "shirt",
    "calendar_dollar",
    "gift",
    "shopping_cart",
    "box",
    // Text
    "ballpen",
    "language",
    // Devices
    "device_speaker",
    "access_point",
    "device_laptop",
    "device_gamepad",
    "blender",
    // Vehicles
    "aerial_lift",
    "motorbike",
    "air_balloon",
    "bus",
    "backhoe",
    "car",
    "bike",
    "gas_station",
    "garden_cart",
    // Food
    "apple",
    "burger",
    "glass_full",
    "glass_gin",
    "cup",
    "carrot",
    "bottle",
    "ice_cream",
    "lemon_2",
    "milk",
    "pizza",
    "glass_cocktail",
    "baguette",
    "cake",
    "bubble_tea",
    "meat",
    "lemon",
    "cheese",
    "bread",
    // Games
    "axe",
    "horse_toy",
    "play_card",
    "piano",
    // Map
    "beach",
    "world",
    "masks_theater",
    "tree",
    "anchor",
    // Development
    "ai",
    "apps",
    "terminal_2",
    "bug",
    // Media
    "movie",
    "radio",
    "video",
    "microphone",
    "music",
    "photo",
    "speakerphone",
    // Health
    "dental",
    "flask",
    "pill",
    "bandage",
    "first_aid_kit",
    "skull",
    "massage",
    "brain",
    "smoking",
    "baby_carriage",
    "eyeglass",
    //
    "award",
    "shovel",
    "armchair",
    "umbrella",
    "gavel",
    "poo",
    "friends",
    "alien",
    "briefcase",
    "armchair_2",
    "sofa",
    "binoculars",
    "man",
    "moneybag",
    "paw",
    "sos",
    "activity",
    "bath",
    "device_watch",
    "lighter",
    // Weather
    "snowflake",
    "flare",
    "sun",
    "cloud",
    // Sport
    "chess_knight",
    "ball_bowling",
    "ball_tennis",
    "ball_baseball",
    "ball_basketball",
    "golf",
    "ball_football",
    "barbell",
    "ball_american_football",
    "ping_pong",
    "chess",
    "ice_skating",
    "ball_volleyball",
    "chess_king",
    // Nature
    "christmas_tree",
    "leaf",
    "cherry",
    "cannabis",
    // Symbols
    "venus",
    "radioactive",
    "mars",
    "yin_yang",
    // Design
    "scissors",
    "cards",
    "cut",
    "brush",
    // Animals
    "cat",
    "pig_money",
    "spider",
    // Document
    "book_2",
    "book",
    "books",
    // System
    "lock",
    "alert_triangle",
    // Communication
    "mail",
)

val categorizedIcons = Res.allDrawableResources.filterKeys {
    it in categorizedIconNames
}